import type { Metadata } from "next";
import "./globals.css";
import HomePageBackground from "./components/home-page-background";
import Header from "./components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HomePageBackground />
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
